#!/bin/bash

# usage: test http://127.0.0.1:2001/web/#/dashboard

set -e

if [ ! x$1 == x ]; then
  if [ `curl -I -s $1|head -1|cut -d" " -f2` == "200" ]; then
    echo -e "\033[32m√\033[0m\t1 test(s) passed."
    exit 0
  else
    echo -e "\033[31mㄨ\033[0m\t1 test(s) failed."
    exit 1
  fi
else
  echo -e "\033[31mErr: No test url specified.\033[0m"
  exit 2
fi
